config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  scope '(:locale)', locale: /en|es/ do
    root to: 'home#index'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get '/dashboard', to: 'dashboard#index'
  get '/settings', to: 'settings#index'
  put '/settings', to: 'settings#update'
  resources :qr_menus, only: :show
  resources :qr_codes, only: :show
  resources :menus, only: %i[new create destroy update show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/menu.rb
class Menu < ApplicationRecord
  belongs_to :user

  has_many :menu_items, dependent: :destroy
  validates :sheet_key, presence: true
  validates :title, presence: true
  def self.create_with_sheet_key(user:, sheet_key:)
    credentials_file = GoogleDrive::Session.from_config('sheetmenu-362021-8b3508189548.json.erb')
    spreadsheet = credentials_file.spreadsheet_by_key(sheet_key)
    worksheet = spreadsheet.worksheets[0]
    keys = worksheet.rows.first
    items = worksheet.rows[1..-1]
    keys = keys.map { |key| key.parameterize(separator: '_') }.map(&:to_sym)
    menu = Menu.new(user:, title: spreadsheet.title, sheet_key:)

    ActiveRecord::Base.transaction do
      menu.save!
      menu_item_attrs = items.map do |item|
        {
          category: item[keys.find_index(:category)],
          item_name: item[keys.find_index(:item_name)],
          description: item[keys.find_index(:description)],
          price: item[keys.find_index(:price)],
          image_url: item[keys.find_index(:image_url)],
          menu_id: menu.id
        }
      end
      MenuItem.upsert_all(menu_item_attrs)
    end
    menu
  end

  def sync!
    credentials_file = GoogleDrive::Session.from_config('sheetmenu-362021-8b3508189548.json.erb')
    spreadsheet = credentials_file.spreadsheet_by_key(sheet_key)
    worksheet = spreadsheet.worksheets[0]
    keys = worksheet.rows.first
    items = worksheet.rows[1..-1]
    keys = keys.map { |key| key.parameterize(separator: '_') }.map(&:to_sym)
    ActiveRecord::Base.transaction do
      save!
      menu_item_attrs = items.map do |item|
        {
          category: item[keys.find_index(:category)],
          item_name: item[keys.find_index(:item_name)],
          description: item[keys.find_index(:description)],
          price: item[keys.find_index(:price)],
          image_url: item[keys.find_index(:image_url)],
          menu_id: id
        }
      end
      MenuItem.upsert_all(menu_item_attrs, unique_by: %i[menu_id item_name])
      item_names = items.map { |item| item[keys.find_index(:item_name)] }
      items_names_to_delete = MenuItem.pluck(:item_name) - item_names
      menu_items.where(item_name: items_names_to_delete).destroy_all
    end
    self
  end

  def to_qrcode
    RQRCode::QRCode.new
  end
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
  belongs_to :menu
  validates :item_name, presence: true
  validates :price, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: %i[facebook]

  has_many :menus, dependent: :destroy
  def self.from_omniauth(auth)
    puts auth.info
    user = User.where(email: auth.info.email).first
    user ||= User.create!(provider: auth.provider, uid: auth.uid, email: auth.info.email,
                          password: Devise.friendly_token[0, 20])
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :info, :error, :warning
  before_action :set_locale

  private

  def set_locale
    I18n.locale = extract_locale || I18n.default_locale
  end

  def extract_locale
    parsed_locale = params[:locale]
    I18n.available_locales.map(&:to_s).include?(parsed_locale) ? parsed_locale : nil
  end
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

class DashboardController < ApplicationController
  before_action :authenticate_user!
  def index
    @menus = current_user.menus
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @menus = Menu.all
    redirect_to dashboard_path if user_signed_in?
  end
end

app/controllers/menus_controller.rb
# frozen_string_literal: true

class MenusController < ApplicationController
  before_action :authenticate_user!
  def new
    @menu = Menu.new
  end

  def create
    @menu = Menu.create_with_sheet_key(user: current_user, sheet_key: menu_params[:sheet_key])
    if @menu.persisted?
      flash[:notice] = 'Menu Created'
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def show
    @menu = Menu.find(params[:id])
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "menu-#{@menu.created_at.strftime('%Y-%m-%d')}",
               title: @menu.title,
               template: 'menus/showPDF', layout: 'pdf', page_size: 'Letter',
               header: { html: { template: 'menus/header', formats: [:html] } }, formats: [:html]
      end
    end
  end

  def update
    @menu = Menu.find(params[:id])
    @menu.sync!
    flash[:notice] = 'Menu Synchronized correctly'
    redirect_to dashboard_path
  end

  def destroy
    @menu = Menu.find(params[:id])
    @menu.destroy
    flash[:notice] = 'Menu Deleted'
    redirect_to dashboard_path
  end

  private

  def menu_params
    params.require(:menu).permit(:sheet_key)
  end
end

app/controllers/qr_codes_controller.rb
# frozen_string_literal: true

class QrCodesController < ApplicationController
  def show
    @menu = Menu.find(params[:id])
  end
end

app/controllers/qr_menus_controller.rb
# frozen_string_literal: true

class QrMenusController < ApplicationController
  layout 'qr_menus'
  def show
    @menu = Menu.find(params[:id])
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "menu-#{@menu.created_at.strftime('%Y-%m-%d')}",
               title: @menu.title,
               template: 'menus/showPDF', layout: 'pdf', page_size: 'Letter',
               header: { html: { template: 'menus/header', formats: [:html] } }, formats: [:html]
      end
    end
  end
end

app/controllers/settings_controller.rb
# frozen_string_literal: true

class SettingsController < ApplicationController
  before_action :authenticate_user!
  def index; end

  def update
    current_user.update(settings_params)
    bypass_sign_in(current_user)
    flash[:notice] = 'User Settings updated'
    redirect_to dashboard_path
  end

  private

  def settings_params
    params.require(:settings).permit(:email, :password)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env['omniauth.auth'])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth'].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/alert_helper.rb
module AlertHelper
  def build_alert_classes(alert_type)
    classes = 'alert alert-dismissable '
    case alert_type.to_sym
    when :alert, :danger, :error, :validation_errors
        classes += 'alert-danger'
    when :warning, :todo
        classes += 'alert-warning'
    when :notice, :success
        classes += 'alert-success'
    else
        classes += 'alert-info'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
  def dashboard_header_class(_controller)
    default_class = 'nav-link block pr-2 lg:px-2 py-6 px-4 hover:text-gray-700 transition duration-150 ease-in-out border-b-2'
    active_class = 'border-indigo-700 text-indigo-700 focus:text-indigo-800 '
    inactive_class = 'border-transparent text-gray-600 focus:text-gray-700 '
    if controller_name == _controller
      active_class + default_class
    else
      inactive_class + default_class
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/dashboard/index.html.erb
<div class="flex py-10 bg-gray-100">
  <div class="flex bg-white w-8/12 mx-auto justify-between p-4 rounded-md">
    <div class="block">
      <h1 class="font-medium">Menus</h1>
      <p>A list of all menus you created</p>
    </div>
    <%= link_to new_menu_path, class: 'justify-center flex items-center inline-block px-6 py-2.5 bg-blue-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out' do %>
      New Menu
    <% end %>
  </div>
</div>
<% if @menus.empty? %>
  <div class="flex mt-5 w-10/12 mx-auto text-center justify-center">
    <p>You dont have any menu</p>
    <p>crate one by clicking the "New Menu" Button</p>
  </div>
<% else %>
  <div class="table mt-5 w-10/12 mx-auto">
    <div class="flex flex-col">
      <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
        <div class="py-2 inline-block min-w-full sm:px-6 lg:px-8">
          <div class="overflow-hidden">
            <table class="min-w-full">
              <thead class="bg-white border-b">
                <tr>
                  <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">
                    #
                  </th>
                  <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">
                    Title
                  </th>
                  <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">
                    Sheet Key
                  </th>
                  <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">
                  </th>
                </tr>
              </thead>
              <tbody>
                <% @menus.each do |menu| %>
                  <tr class="bg-gray-100 border-b">
                    <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                      <%= menu.id %>
                    </td>
                    <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                      <%= menu.title %>
                    </td>
                    <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                      <%= menu.sheet_key %>
                    </td>
                    <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                      <%= link_to qr_code_path(menu), target: :_blank, class: 'text-green-700 font-medium hover:text-green-600 cursor-pointer mr-2' do %>
                        Print QR Code
                      <% end %>
                      <%= link_to menu_path(menu, format: :pdf), target: :_blank, class: 'text-pink-700 font-medium hover:text-green-600 cursor-pointer mr-2' do %>
                        View PDF
                      <% end %>
                      <%= link_to  menu_path(menu),  target: :_blank, class: 'text-blue-700 font-medium hover:text-blue-600 cursor-pointer' do %>
                        View
                      <% end %>
                      <%= link_to menu_path(menu), data: { "turbo-method": :put }, class: 'text-green-700 font-medium hover:text-green-600 cursor-pointer ml-2' do %>
                        Sync
                      <% end %>
                      <%= link_to menu_path(menu), data: { "turbo-method": :delete} , class: 'text-red-700 font-medium hover:text-red-600 cursor-pointer ml-2' do %>
                        Delete
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/home/index.html.erb
<%= render 'layouts/header' %>
<div class="py-10 bg-beige-300 flex justify-center flex-col items-center w-11/12 md:w-7/12 mx-auto">
  <h2 class="text-xl font-bold leading-5 mb-3 uppercase">Recent menus</h2>
  <p>Checkout our recents digital menus that our users have created</p>
</div>
<div class="mb-10 flex justify-center w-11/12 md:w-7/12 mx-auto">
  <% if @menus.present? %>
    <ul class="list flex w-full">
      <% @menus.each do |menu| %>
        <li class="w-full md:w-4/12 text-center">
          <div class="space-y-3 w-full text-center">
            <%= link_to qr_menu_path(menu), class: 'link' do %>
              <%= image_tag menu.menu_items.sample.image_url, alt:'', class: 'mx-auto h-40 w-40 rounded object-cover' %>
            <% end %>
            <div class="space-y-2">
              <div class="space-y-1 text-lg leading-6 font-medium">
                <h3 class="mb-2"><%=link_to menu.title, qr_menu_path(menu), class:'' %></h3>
                <p class="text-indigo-600 mt-2"><%= link_to "QR Code", qr_code_path(menu) %></p>
                <p class="text-indigo-600 mt-2"><%= link_to "PDF Version", qr_menu_path(menu, format: :pdf) %></p>
              </div>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  <% else %>
    <strong>There are no menus yet</strong>
  <% end %>
</div>

app/views/layouts/_dashboard-navbar.html.erb
<!-- Navbar -->
<nav class="navbar navbar-expand-lg shadow-md bg-white relative flex items-center w-full justify-between">
  <div class="px-6 w-full flex flex-wrap items-center justify-between md:flex-row-reverse md:w-4/5 mx-auto">
    <div class="flex items-center w-full flex-row justify-between md:justify-center md:w-2/12">
      <button
        class="navbar-toggler border-0 py-3 lg:hidden leading-none text-xl bg-transparent text-gray-600 hover:text-gray-700 focus:text-gray-700 transition-shadow duration-150 ease-in-out mr-2"
        type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContentY"
        aria-controls="navbarSupportedContentY" aria-expanded="false" aria-label="Toggle navigation">
        <svg aria-hidden="true" focusable="false" data-prefix="fas" class="w-5" role="img"
          xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
          <path fill="currentColor"
            d="M16 132h416c8.837 0 16-7.163 16-16V76c0-8.837-7.163-16-16-16H16C7.163 60 0 67.163 0 76v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16z">
          </path>
        </svg>
      </button>
      <!-- User Mobile Section -->
      <div class="user-section">
        <% if signed_in? %>
          <div class="dropdown relative">
            <a class="dropdown-toggle flex items-center hidden-arrow" href="#" id="dropdownMenuButton2" role="button"
            data-bs-toggle="dropdown" aria-expanded="false">
              <img src="https://mdbootstrap.com/img/new/avatars/2.jpg" class="rounded-full"
              style="height: 25px; width: 25px" alt="" loading="lazy" />
            </a>
            <ul
            class="dropdown-menu min-w-max absolute hidden bg-white text-base z-50 float-left py-2 list-none text-left shadow-lg mt-1 hidden m-0 bg-clip-padding border-none left-auto right-0"
            aria-labelledby="dropdownMenuButton2">
              <li>
                <%= link_to settings_path, class: 'dropdown-item text-md py-2 px-6 font-normal block w-full whitespace-nowrap bg-transparent text-gray-700 hover:bg-gray-100' do %>
                  Edit profile
                <% end %>
              </li>
              <li>
                <%= button_to "Log out", destroy_user_session_path, method: :delete , class: 'dropdown-item text-md py-2 px-6 font-normal block w-full whitespace-nowrap bg-transparent text-gray-700 hover:bg-gray-100' %>
              </li>
            </ul>
          </div>
        <% else %>
          <%= link_to 'Login', new_user_session_path, class: 'btn px-6 py-2 bg-blue-500 hover:bg-blue-400 transition duration-150 ease-in  hover:ease-out mr-3 text-white rounded' %>
        <% end %>
      </div>
    </div>
    <div class="navbar-collapse collapse grow items-center md:w-10/12" id="navbarSupportedContentY">
      <ul class="navbar-nav mr-auto lg:flex lg:flex-row">
        <li class="nav-item">
          <%= link_to dashboard_path, class: dashboard_header_class("dashboard") do %>
            Dashboard
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to settings_path, class: dashboard_header_class("settings") do %>
            Settings
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>
<!-- Navbar -->

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
  <% if type == "notice" %>
    <div class="alert bg-blue-100 rounded-lg py-3 px-6 text-base inline-flex justify-center items-center flex w-full alert-dismissible fade show" role="alert">
      <div class="w-9/12 mx-auto flex justify-around items-center">
        <div class="message w-4/5 text-blue-800">
          <%= message %>
        </div>
        <div class="button w-1/5 flex justify-center">
          <button type="button" class="btn-close box-content w-4 h-4 p-1 ml-auto text-yellow-900 border-none rounded-none opacity-50 focus:shadow-none focus:outline-none focus:opacity-100 hover:text-yellow-900 hover:opacity-75 hover:no-underline" data-bs-dismiss="alert" aria-label="Close">
            <svg width="20px" height="20px" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
              <path fill="none" stroke="#000" stroke-width="2" d="M3,3 L21,21 M3,21 L21,3"/>
            </svg>
          </button>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/layouts/_header.erb
 <!-- Background image -->
<div class="relative overflow-hidden bg-no-repeat bg-cover h-screen" style="
    background-position: 50%;
    background-image: url('https://cdn.pixabay.com/photo/2017/06/06/22/46/mediterranean-cuisine-2378758_1280.jpg');
    height: 80vh;
  ">
  <div class="absolute top-0 right-0 bottom-0 left-0 w-full h-full overflow-hidden bg-fixed h-screen"
      style="background-color: rgba(0, 0, 0, 0.75)">
    <div class="flex justify-center items-center h-full">
      <div class="text-center text-white px-6 md:px-12">
        <h1 class="text-4xl font-bold mt-0 mb-4"> <%= t('title')%></h1>
        <h3 class="text-5xl font-bold mb-3">Google Sheet</h3>
        <p class="mt-3 mb-4"><%= t('headline')  %></p>
        <%= link_to new_user_registration_path, class: 'inline-block px-6 py-2.5 border-2 border-white text-white font-medium text-xs leading-tight uppercase rounded hover:bg-black hover:bg-opacity-5 focus:outline-none focus:ring-0 transition duration-150 ease-in-out' do %>
          <%= t('get_started')  %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<!-- Background image -->

app/views/layouts/_navbar.html.erb
<!-- Navbar -->
<nav class="navbar navbar-expand-lg shadow-md py-2 bg-white relative flex items-center w-full justify-between">
  <div class="px-6 w-full flex flex-wrap items-center justify-between md:flex-row-reverse md:w-3/5 mx-auto">
    <div class="flex items-center w-full flex-row justify-between md:justify-center md:w-3/12">
      <button
        class="navbar-toggler border-0 py-3 lg:hidden leading-none text-xl bg-transparent text-gray-600 hover:text-gray-700 focus:text-gray-700 transition-shadow duration-150 ease-in-out mr-2"
        type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContentY"
        aria-controls="navbarSupportedContentY" aria-expanded="false" aria-label="Toggle navigation">
        <svg aria-hidden="true" focusable="false" data-prefix="fas" class="w-5" role="img"
          xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
          <path fill="currentColor"
            d="M16 132h416c8.837 0 16-7.163 16-16V76c0-8.837-7.163-16-16-16H16C7.163 60 0 67.163 0 76v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16z">
          </path>
        </svg>
      </button>
      <% if I18n.locale == :es %>
        <%= link_to locale: "en"  do %>
          <span class="btn px-2 py-2 border mr-3 cursor-pointer rounded border-violet-800 text-sm">
            EN
          </span>
        <% end %>
      <% else %>
        <%= link_to locale: "es"  do %>
          <span class="btn px-2 py-2 border mr-3 cursor-pointer rounded border-violet-800	text-sm">
            ES
          </span>
        <% end %>
      <% end %>
      <!-- User Mobile Section -->
      <div class="user-section">
        <% if signed_in? %>
          <div class="dropdown relative">
            <a class="dropdown-toggle flex items-center hidden-arrow" href="#" id="dropdownMenuButton2" role="button"
            data-bs-toggle="dropdown" aria-expanded="false">
              <img src="https://mdbootstrap.com/img/new/avatars/2.jpg" class="rounded-full"
              style="height: 25px; width: 25px" alt="" loading="lazy" />
            </a>
            <ul
            class="dropdown-menu min-w-max absolute hidden bg-white text-base z-50 float-left py-2 list-none text-left rounded-lg shadow-lg mt-1 hidden m-0 bg-clip-padding border-none left-auto right-0"
            aria-labelledby="dropdownMenuButton2">
              <li>
                <a class="dropdown-item text-sm py-2 px-6 font-normal block w-full whitespace-nowrap bg-transparent text-gray-700 hover:bg-gray-100"
                href="#">Edit Profile</a>
              </li>
              <li>
                <%= button_to "Log out", destroy_user_session_path, method: :delete , class: 'dropdown-item text-sm py-2 px-6 font-normal block w-full whitespace-nowrap bg-transparent text-gray-700 hover:bg-gray-100' %>
              </li>
            </ul>
          </div>
        <% else %>
          <%= link_to 'Login', new_user_session_path, class: 'btn px-12 py-2 bg-indigo-500 hover:bg-indigo-400 transition duration-150 ease-in  hover:ease-out mr-3 text-white rounded' %>
        <% end %>
      </div>
    </div>
    <div class="navbar-collapse collapse grow items-center md:w-9/12" id="navbarSupportedContentY">
      <ul class="navbar-nav mr-auto lg:flex lg:flex-row">
        <li class="nav-item">
          <%= link_to root_path, class: 'nav-link block pr-2 lg:px-2 py-2 text-gray-600 hover:text-gray-700 focus:text-gray-700 transition duration-150 ease-in-out' do %>
            Home
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>
<!-- Navbar -->

app/views/layouts/pdf.html.erb
<!doctype html>
<html>
  <head>
    <meta charset='utf-8' />
    <%= wicked_pdf_stylesheet_link_tag "pdf" -%>
    <%#= wicked_pdf_javascript_include_tag "number_pages" %>
  </head>
  <body onload='number_pages'>
    <div id="header">
      <%#= wicked_pdf_image_tag 'mysite.jpg' %>
    </div>
    <div id="content">
      <%= yield %>
    </div>
  </body>
</html>

app/views/menus/header.html.erb
<!--Aqui se puede poner un logo o una imagen -->
<h1 class="heading"><%= @menu.title %></h1>

app/views/menus/show.html.erb
<%= render @menu %>

app/views/qr_codes/show.html.erb
<%
qr_code = RQRCode::QRCode.new(qr_menu_url(@menu, format: :pdf))

%>
<div class="flex justify-center py-6 my-6 flex-col w-full px-12 md:w-8/12 mx-auto items-center">
  <h1 class="heading mb-2">QR Code</h1>
  <h2 class="text-lg font-bold mb-2"><%= link_to @menu.title, qr_menu_path(@menu), class:'text-bold text-green-700 hover:text-green-800' %></h2>
  <% if ActiveModel::Type::Boolean.new.cast(params[:multiple]) %>
    <%= link_to qr_code_path(@menu, multiple: false), class: 'mb-6' do %>
      View / Print Singe Code
    <% end %>
    <div class="grid grid-cols-5 gap-4">
      <% svg = qr_code.as_svg(
        color: "000",
        shape_rendering: "crispEdges",
        module_size: 5,
        standalone: true,
        use_path: true
      ) %>
      <%50.times do  %>
        <div class="mb-14 mr-5">
          <%=svg.html_safe%>
        </div>
      <% end %>
    </div>
  <% else %>
    <%= link_to qr_code_path(@menu, multiple: true), class: 'mb-6' do %>
      View / Print Multiple QR Codes
    <% end %>
    <% svg = qr_code.as_svg(
        color: "000",
        shape_rendering: "crispEdges",
        module_size: 8,
        standalone: true,
        use_path: true
      ) %>
    <%=svg.html_safe%>
  <% end %>
</div>

app/views/qr_menus/show.html.erb
<div class="mt-6">
  <%= render @menu %>
</div>

app/views/settings/index.html.erb
<div class="max-w-lg mx-auto pt-10 pb-12 px-4 lg:pb-16">
  <%= form_with model: current_user, scope: :settings,  url: settings_path, method: :put, local: true do |f| %>
    <div class="space-y-6">
      <div>
        <h1 class="heading">
          User Settings
        </h1>
        <p class="mt-1 text-sm text-gray-500">Update your settings below.</p>
      </div>
      <div>
        <%= f.label :email, class: 'block text-sm font-medium text-gray-700' %>
        <%= f.email_field :email, class:'block w-full shadow-sm focus:ring-sky-400 focus:border-sky-400 sm:text-sm border-gray-400 rounded-md mt-3' %>
      </div>
      <div>
        <%= f.label :password, class: 'block text-sm font-medium text-gray-700' %>
        <%= f.password_field :password, class:'block w-full shadow-sm focus:ring-sky-400 focus:border-sky-400 sm:text-sm border-gray-400 rounded-md mt-3' %>
      </div>
      <div class="flex justify-end">
        <%= f.submit "Update Settings", class:'inline-block  w-full cursor-pointer px-6 py-2.5 bg-blue-600 my-3 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out' %>
      </div>
    </div>
  <% end %>
</div>